#!/usr/bin/python3

import sys
import time

def factorize_number(number):
    factors = []
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            factors.append((i, number // i))
    return factors

def factorize_file(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorize_number(number)
            for factor_pair in factors:
                print(f"{number}={factor_pair[0]}*{factor_pair[1]}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)
    file_path = sys.argv[1]
    factorize_file(file_path)
